name: amazon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  badges: ^2.0.2
  carousel_slider: ^4.2.1
  cloudinary: ^1.2.0
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  velocity_x: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/Images/